name: Node.js CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and package Docker image
        run: |
          docker build -t my-node-app .
          docker tag my-node-app:latest prateek9814/my-node-app:latest
          docker push prateek9814/my-node-app:latest

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ./kubeconfig
          export KUBECONFIG=./kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl rollout status deployment/my-node-app

      #- name: Check deployment status
       # env:
        #  KUBECONFIG: ${{ secrets.KUBECONFIG }}
        #run: |
         # if ! kubectl rollout status deployment/my-node-app; then
         #   echo "Deployment failed, rolling back..."
          #  kubectl rollout undo deployment/my-node-app
          #fi
          
